apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: tank
spec:
  type: ClusterIP
  ports:
    - port: 2379
      targetPort: 2379
      protocol: TCP
      name: client
    - port: 2380
      targetPort: 2380
      protocol: TCP
      name: cluster
  selector:
    app: etcd

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: tank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      securityContext:
      containers:
        - name: etcd
          image: bitnami/etcd:latest
          imagePullPolicy: IfNotPresent
          command: ["etcd",  "--data-dir=/var/lib/etcd/data", "--listen-peer-urls=http://127.0.0.1:2380", "--listen-client-urls=http://0.0.0.0:2379", "--advertise-client-urls=http://0.0.0.0:2379", "--client-cert-auth=false" ]
          ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: cluster
              protocol: TCP
          securityContext:
            runAsUser: 0  # 解决权限问题
            runAsGroup: 0
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib/etcd/
      volumes:
        - name: etcd-data
          hostPath:
            path: /root/tank/etcd/
