// Code generated by Kitex v0.11.3. DO NOT EDIT.

package homepageservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	homepage "homepage_server/kitex_gen/homepage"
	homepage_service "homepage_server/kitex_gen/homepage_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"get_role_info": kitex.NewMethodInfo(
		getRoleInfoHandler,
		newGetRoleInfoArgs,
		newGetRoleInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"update_role_exp": kitex.NewMethodInfo(
		updateRoleExpHandler,
		newUpdateRoleExpArgs,
		newUpdateRoleExpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	homepageServiceServiceInfo                = NewServiceInfo()
	homepageServiceServiceInfoForClient       = NewServiceInfoForClient()
	homepageServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return homepageServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return homepageServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return homepageServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "HomepageService"
	handlerType := (*homepage_service.HomepageService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "homepage_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func getRoleInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(homepage.GetRoleInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(homepage_service.HomepageService).GetRoleInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRoleInfoArgs:
		success, err := handler.(homepage_service.HomepageService).GetRoleInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRoleInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRoleInfoArgs() interface{} {
	return &GetRoleInfoArgs{}
}

func newGetRoleInfoResult() interface{} {
	return &GetRoleInfoResult{}
}

type GetRoleInfoArgs struct {
	Req *homepage.GetRoleInfoReq
}

func (p *GetRoleInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRoleInfoArgs) Unmarshal(in []byte) error {
	msg := new(homepage.GetRoleInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRoleInfoArgs_Req_DEFAULT *homepage.GetRoleInfoReq

func (p *GetRoleInfoArgs) GetReq() *homepage.GetRoleInfoReq {
	if !p.IsSetReq() {
		return GetRoleInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRoleInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRoleInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRoleInfoResult struct {
	Success *homepage.GetRoleInfoRsp
}

var GetRoleInfoResult_Success_DEFAULT *homepage.GetRoleInfoRsp

func (p *GetRoleInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRoleInfoResult) Unmarshal(in []byte) error {
	msg := new(homepage.GetRoleInfoRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRoleInfoResult) GetSuccess() *homepage.GetRoleInfoRsp {
	if !p.IsSetSuccess() {
		return GetRoleInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRoleInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*homepage.GetRoleInfoRsp)
}

func (p *GetRoleInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRoleInfoResult) GetResult() interface{} {
	return p.Success
}

func updateRoleExpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(homepage.UpdateRoleExpReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(homepage_service.HomepageService).UpdateRoleExp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateRoleExpArgs:
		success, err := handler.(homepage_service.HomepageService).UpdateRoleExp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateRoleExpResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateRoleExpArgs() interface{} {
	return &UpdateRoleExpArgs{}
}

func newUpdateRoleExpResult() interface{} {
	return &UpdateRoleExpResult{}
}

type UpdateRoleExpArgs struct {
	Req *homepage.UpdateRoleExpReq
}

func (p *UpdateRoleExpArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateRoleExpArgs) Unmarshal(in []byte) error {
	msg := new(homepage.UpdateRoleExpReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateRoleExpArgs_Req_DEFAULT *homepage.UpdateRoleExpReq

func (p *UpdateRoleExpArgs) GetReq() *homepage.UpdateRoleExpReq {
	if !p.IsSetReq() {
		return UpdateRoleExpArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateRoleExpArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateRoleExpArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateRoleExpResult struct {
	Success *homepage.UpdateRoleExpRsp
}

var UpdateRoleExpResult_Success_DEFAULT *homepage.UpdateRoleExpRsp

func (p *UpdateRoleExpResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateRoleExpResult) Unmarshal(in []byte) error {
	msg := new(homepage.UpdateRoleExpRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateRoleExpResult) GetSuccess() *homepage.UpdateRoleExpRsp {
	if !p.IsSetSuccess() {
		return UpdateRoleExpResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateRoleExpResult) SetSuccess(x interface{}) {
	p.Success = x.(*homepage.UpdateRoleExpRsp)
}

func (p *UpdateRoleExpResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateRoleExpResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetRoleInfo(ctx context.Context, Req *homepage.GetRoleInfoReq) (r *homepage.GetRoleInfoRsp, err error) {
	var _args GetRoleInfoArgs
	_args.Req = Req
	var _result GetRoleInfoResult
	if err = p.c.Call(ctx, "get_role_info", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateRoleExp(ctx context.Context, Req *homepage.UpdateRoleExpReq) (r *homepage.UpdateRoleExpRsp, err error) {
	var _args UpdateRoleExpArgs
	_args.Req = Req
	var _result UpdateRoleExpResult
	if err = p.c.Call(ctx, "update_role_exp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
