apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "tank-gateway"
    jwks: |
      {
        "keys": [
          {
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "e": "AQAB",
            "n": "ykv6d/HjVkVvDD2pTfhFLwimpovl/ll05g/jwD1eJSkjiGxvpbpfklgqRdw+sLUagvFzRUxGLvdCuwi6CKQFLxA",
            "kid": "tank-gateway-key"
          }
        ]
      }
    forwardOriginalToken: true
    fromHeaders:
    - name: Authorization
      prefix: "Bearer "
