apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - jwks: |
      {
        "keys": [
          {
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "e": "AQAB",
            "n": "i8brfxk1Rp8MPaU35BS8ISnaLl_1nUOWD43yA9R4lJCjhosbpbp1JYKUXcPrC1GgLxc0VMRi-3QrsI2gikBRyw",
            "kid": "tank-gateway-key"
          }
        ]
      }
    forwardOriginalToken: true
    fromHeaders:
    - name: Authorization
      prefix: "Bearer "
