// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/tank_game_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace TankGameService {
  public static partial class TankGameService
  {
    static readonly string __ServiceName = "tank_game_service.TankGameService";

    static readonly grpc::Marshaller<global::TankGameService.Ping> __Marshaller_tank_game_service_Ping = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TankGameService.Ping.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TankGameService.Pong> __Marshaller_tank_game_service_Pong = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TankGameService.Pong.Parser.ParseFrom);

    static readonly grpc::Method<global::TankGameService.Ping, global::TankGameService.Pong> __Method_ping = new grpc::Method<global::TankGameService.Ping, global::TankGameService.Pong>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ping",
        __Marshaller_tank_game_service_Ping,
        __Marshaller_tank_game_service_Pong);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::TankGameService.TankGameServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TankGameService</summary>
    public abstract partial class TankGameServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::TankGameService.Pong> ping(global::TankGameService.Ping request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TankGameService</summary>
    public partial class TankGameServiceClient : grpc::ClientBase<TankGameServiceClient>
    {
      /// <summary>Creates a new client for TankGameService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TankGameServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TankGameService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TankGameServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TankGameServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TankGameServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::TankGameService.Pong ping(global::TankGameService.Ping request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TankGameService.Pong ping(global::TankGameService.Ping request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TankGameService.Pong> pingAsync(global::TankGameService.Ping request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return pingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TankGameService.Pong> pingAsync(global::TankGameService.Ping request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TankGameServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TankGameServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TankGameServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ping, serviceImpl.ping).Build();
    }

  }
}
#endregion
