// Code generated by Kitex v0.11.3. DO NOT EDIT.

package servermgrservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	server_mgr "server_manager/kitex_gen/server_mgr"
	server_mgr_service "server_manager/kitex_gen/server_mgr_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"create_server": kitex.NewMethodInfo(
		createServerHandler,
		newCreateServerArgs,
		newCreateServerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"create_ai_client": kitex.NewMethodInfo(
		createAiClientHandler,
		newCreateAiClientArgs,
		newCreateAiClientResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	serverMgrServiceServiceInfo                = NewServiceInfo()
	serverMgrServiceServiceInfoForClient       = NewServiceInfoForClient()
	serverMgrServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return serverMgrServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return serverMgrServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return serverMgrServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ServerMgrService"
	handlerType := (*server_mgr_service.ServerMgrService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "server_mgr_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func createServerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(server_mgr.CreateServerReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(server_mgr_service.ServerMgrService).CreateServer(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateServerArgs:
		success, err := handler.(server_mgr_service.ServerMgrService).CreateServer(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateServerResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateServerArgs() interface{} {
	return &CreateServerArgs{}
}

func newCreateServerResult() interface{} {
	return &CreateServerResult{}
}

type CreateServerArgs struct {
	Req *server_mgr.CreateServerReq
}

func (p *CreateServerArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateServerArgs) Unmarshal(in []byte) error {
	msg := new(server_mgr.CreateServerReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateServerArgs_Req_DEFAULT *server_mgr.CreateServerReq

func (p *CreateServerArgs) GetReq() *server_mgr.CreateServerReq {
	if !p.IsSetReq() {
		return CreateServerArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateServerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateServerArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateServerResult struct {
	Success *server_mgr.CreateServerRsp
}

var CreateServerResult_Success_DEFAULT *server_mgr.CreateServerRsp

func (p *CreateServerResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateServerResult) Unmarshal(in []byte) error {
	msg := new(server_mgr.CreateServerRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateServerResult) GetSuccess() *server_mgr.CreateServerRsp {
	if !p.IsSetSuccess() {
		return CreateServerResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateServerResult) SetSuccess(x interface{}) {
	p.Success = x.(*server_mgr.CreateServerRsp)
}

func (p *CreateServerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateServerResult) GetResult() interface{} {
	return p.Success
}

func createAiClientHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(server_mgr.CreateAiClientReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(server_mgr_service.ServerMgrService).CreateAiClient(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateAiClientArgs:
		success, err := handler.(server_mgr_service.ServerMgrService).CreateAiClient(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateAiClientResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateAiClientArgs() interface{} {
	return &CreateAiClientArgs{}
}

func newCreateAiClientResult() interface{} {
	return &CreateAiClientResult{}
}

type CreateAiClientArgs struct {
	Req *server_mgr.CreateAiClientReq
}

func (p *CreateAiClientArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateAiClientArgs) Unmarshal(in []byte) error {
	msg := new(server_mgr.CreateAiClientReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateAiClientArgs_Req_DEFAULT *server_mgr.CreateAiClientReq

func (p *CreateAiClientArgs) GetReq() *server_mgr.CreateAiClientReq {
	if !p.IsSetReq() {
		return CreateAiClientArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateAiClientArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateAiClientArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateAiClientResult struct {
	Success *server_mgr.CreateAiClientRsp
}

var CreateAiClientResult_Success_DEFAULT *server_mgr.CreateAiClientRsp

func (p *CreateAiClientResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateAiClientResult) Unmarshal(in []byte) error {
	msg := new(server_mgr.CreateAiClientRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateAiClientResult) GetSuccess() *server_mgr.CreateAiClientRsp {
	if !p.IsSetSuccess() {
		return CreateAiClientResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateAiClientResult) SetSuccess(x interface{}) {
	p.Success = x.(*server_mgr.CreateAiClientRsp)
}

func (p *CreateAiClientResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateAiClientResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateServer(ctx context.Context, Req *server_mgr.CreateServerReq) (r *server_mgr.CreateServerRsp, err error) {
	var _args CreateServerArgs
	_args.Req = Req
	var _result CreateServerResult
	if err = p.c.Call(ctx, "create_server", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAiClient(ctx context.Context, Req *server_mgr.CreateAiClientReq) (r *server_mgr.CreateAiClientRsp, err error) {
	var _args CreateAiClientArgs
	_args.Req = Req
	var _result CreateAiClientResult
	if err = p.c.Call(ctx, "create_ai_client", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
