// Code generated by Kitex v0.11.3. DO NOT EDIT.

package rankingservice

import (
	"context"
	ranking "gate_way_module/kitex_gen/ranking"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UpdateScore(ctx context.Context, Req *ranking.UpdateScoreReq, callOptions ...callopt.Option) (r *ranking.UpdateScoreRsp, err error)
	GetUserRank(ctx context.Context, Req *ranking.GetUserRankReq, callOptions ...callopt.Option) (r *ranking.GetUserRankRsp, err error)
	GetRankRange(ctx context.Context, Req *ranking.GetRankRangeReq, callOptions ...callopt.Option) (r *ranking.GetRankRangeRsp, err error)
	BatchGetUserRank(ctx context.Context, Req *ranking.BatchGetUserRankReq, callOptions ...callopt.Option) (r *ranking.BatchGetUserRankRsp, err error)
	GetRankingStats(ctx context.Context, Req *ranking.GetRankingStatsReq, callOptions ...callopt.Option) (r *ranking.GetRankingStatsRsp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRankingServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRankingServiceClient struct {
	*kClient
}

func (p *kRankingServiceClient) UpdateScore(ctx context.Context, Req *ranking.UpdateScoreReq, callOptions ...callopt.Option) (r *ranking.UpdateScoreRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateScore(ctx, Req)
}

func (p *kRankingServiceClient) GetUserRank(ctx context.Context, Req *ranking.GetUserRankReq, callOptions ...callopt.Option) (r *ranking.GetUserRankRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserRank(ctx, Req)
}

func (p *kRankingServiceClient) GetRankRange(ctx context.Context, Req *ranking.GetRankRangeReq, callOptions ...callopt.Option) (r *ranking.GetRankRangeRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRankRange(ctx, Req)
}

func (p *kRankingServiceClient) BatchGetUserRank(ctx context.Context, Req *ranking.BatchGetUserRankReq, callOptions ...callopt.Option) (r *ranking.BatchGetUserRankRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetUserRank(ctx, Req)
}

func (p *kRankingServiceClient) GetRankingStats(ctx context.Context, Req *ranking.GetRankingStatsReq, callOptions ...callopt.Option) (r *ranking.GetRankingStatsRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRankingStats(ctx, Req)
}
