// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0--rc2
// source: proto/match_proto.proto

package match_proto

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "server_manager/kitex_gen/common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchReq) Reset() {
	*x = MatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchReq) ProtoMessage() {}

func (x *MatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchReq.ProtoReflect.Descriptor instead.
func (*MatchReq) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_proto_rawDescGZIP(), []int{0}
}

type MatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code common.ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
}

func (x *MatchResp) Reset() {
	*x = MatchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResp) ProtoMessage() {}

func (x *MatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResp.ProtoReflect.Descriptor instead.
func (*MatchResp) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_proto_rawDescGZIP(), []int{1}
}

func (x *MatchResp) GetCode() common.ErrorCode {
	if x != nil {
		return x.Code
	}
	return common.ErrorCode(0)
}

type MatchInfoNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R []string `protobuf:"bytes,1,rep,name=r,proto3" json:"r,omitempty"`
	B []string `protobuf:"bytes,2,rep,name=b,proto3" json:"b,omitempty"`
}

func (x *MatchInfoNtf) Reset() {
	*x = MatchInfoNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchInfoNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfoNtf) ProtoMessage() {}

func (x *MatchInfoNtf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfoNtf.ProtoReflect.Descriptor instead.
func (*MatchInfoNtf) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_proto_rawDescGZIP(), []int{2}
}

func (x *MatchInfoNtf) GetR() []string {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *MatchInfoNtf) GetB() []string {
	if x != nil {
		return x.B
	}
	return nil
}

type GameInfoNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameAddr string `protobuf:"bytes,1,opt,name=gameAddr,proto3" json:"gameAddr,omitempty"`
	GamePort int32  `protobuf:"varint,2,opt,name=gamePort,proto3" json:"gamePort,omitempty"`
}

func (x *GameInfoNtf) Reset() {
	*x = GameInfoNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfoNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoNtf) ProtoMessage() {}

func (x *GameInfoNtf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoNtf.ProtoReflect.Descriptor instead.
func (*GameInfoNtf) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_proto_rawDescGZIP(), []int{3}
}

func (x *GameInfoNtf) GetGameAddr() string {
	if x != nil {
		return x.GameAddr
	}
	return ""
}

func (x *GameInfoNtf) GetGamePort() int32 {
	if x != nil {
		return x.GamePort
	}
	return 0
}

type PveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PveReq) Reset() {
	*x = PveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_proto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveReq) ProtoMessage() {}

func (x *PveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveReq.ProtoReflect.Descriptor instead.
func (*PveReq) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_proto_rawDescGZIP(), []int{4}
}

type PveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code common.ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
}

func (x *PveResp) Reset() {
	*x = PveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_proto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveResp) ProtoMessage() {}

func (x *PveResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveResp.ProtoReflect.Descriptor instead.
func (*PveResp) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_proto_rawDescGZIP(), []int{5}
}

func (x *PveResp) GetCode() common.ErrorCode {
	if x != nil {
		return x.Code
	}
	return common.ErrorCode(0)
}

var File_proto_match_proto_proto protoreflect.FileDescriptor

var file_proto_match_proto_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0a, 0x0a, 0x08, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x22, 0x32, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x74, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x01, 0x62, 0x22, 0x45, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x4e, 0x74, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x41, 0x64, 0x64,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x08, 0x0a,
	0x06, 0x50, 0x76, 0x65, 0x52, 0x65, 0x71, 0x22, 0x30, 0x0a, 0x07, 0x50, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6b, 0x69, 0x74, 0x65,
	0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_match_proto_proto_rawDescOnce sync.Once
	file_proto_match_proto_proto_rawDescData = file_proto_match_proto_proto_rawDesc
)

func file_proto_match_proto_proto_rawDescGZIP() []byte {
	file_proto_match_proto_proto_rawDescOnce.Do(func() {
		file_proto_match_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_match_proto_proto_rawDescData)
	})
	return file_proto_match_proto_proto_rawDescData
}

var file_proto_match_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_match_proto_proto_goTypes = []interface{}{
	(*MatchReq)(nil),      // 0: match_proto.MatchReq
	(*MatchResp)(nil),     // 1: match_proto.MatchResp
	(*MatchInfoNtf)(nil),  // 2: match_proto.MatchInfoNtf
	(*GameInfoNtf)(nil),   // 3: match_proto.GameInfoNtf
	(*PveReq)(nil),        // 4: match_proto.PveReq
	(*PveResp)(nil),       // 5: match_proto.PveResp
	(common.ErrorCode)(0), // 6: common.ErrorCode
}
var file_proto_match_proto_proto_depIdxs = []int32{
	6, // 0: match_proto.MatchResp.code:type_name -> common.ErrorCode
	6, // 1: match_proto.PveResp.code:type_name -> common.ErrorCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_match_proto_proto_init() }
func file_proto_match_proto_proto_init() {
	if File_proto_match_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_match_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchInfoNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfoNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_proto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_proto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_match_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_match_proto_proto_goTypes,
		DependencyIndexes: file_proto_match_proto_proto_depIdxs,
		MessageInfos:      file_proto_match_proto_proto_msgTypes,
	}.Build()
	File_proto_match_proto_proto = out.File
	file_proto_match_proto_proto_rawDesc = nil
	file_proto_match_proto_proto_goTypes = nil
	file_proto_match_proto_proto_depIdxs = nil
}

var _ context.Context
