// Code generated by Kitex v0.11.3. DO NOT EDIT.
package gatewayservice

import (
	server "github.com/cloudwego/kitex/server"
	gateway_service "match_server/kitex_gen/gateway_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler gateway_service.GatewayService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler gateway_service.GatewayService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
