using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEditor.iOS.Xcode.Extensions;
using UnityEngine;

namespace Dirichlet.Mediation.Editor
{
    /// <summary>
    /// iOS build post-processor for Dirichlet Mediation SDK.
    /// Generates dynamic Podfile based on adapter settings and runs CocoaPods installation.
    /// </summary>
    public class DirichletMediationIOSPostProcessor
    {
        private const string SDKVersion = "4.1.2.0";

        [PostProcessBuild(100)]
        public static void OnPostprocessBuild(BuildTarget buildTarget, string pathToBuiltProject)
        {
            if (buildTarget != BuildTarget.iOS)
            {
                return;
            }

            Debug.Log("[DirichletMediation] Starting iOS post-process...");

            try
            {
                // 1. Generate Podfile dynamically based on adapter settings
                GeneratePodfile(pathToBuiltProject);

                // 2. Modify Xcode project settings (before pod install)
                ModifyXcodeProject(pathToBuiltProject);

                // 3. Modify Info.plist for required permissions
                ModifyInfoPlist(pathToBuiltProject);

                // 4. Run pod install
                RunPodInstall(pathToBuiltProject);
                
                // 5. Embed dynamic frameworks (after pod install)
                // GDT SDK 使用动态 framework，需要嵌入到主 App
                EmbedDynamicFrameworks(pathToBuiltProject);

                Debug.Log("[DirichletMediation] iOS post-process completed successfully.");
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"[DirichletMediation] iOS post-process failed: {ex.Message}");
            }
        }

        private static void GeneratePodfile(string projectPath)
        {
            // Read adapter settings from EditorPrefs
            // Note: DirichletAdSDK (DRA adapter) is always enabled as core SDK
            var enableCsj = EditorPrefs.GetBool("Dirichlet.iOS.EnableCSJ", true);
            var enableGdt = EditorPrefs.GetBool("Dirichlet.iOS.EnableGDT", true);

            var podfileContent = new StringBuilder();
            podfileContent.AppendLine("# Generated by Dirichlet Mediation Unity Plugin");
            podfileContent.AppendLine("source 'https://github.com/CocoaPods/Specs.git'");
            podfileContent.AppendLine();
            podfileContent.AppendLine("platform :ios, '11.0'");
            podfileContent.AppendLine("use_frameworks!");
            podfileContent.AppendLine();
            
            // 只对 UnityFramework 进行 pod 集成
            // 不声明 Unity-iPhone target，避免 CSJ 等静态库符号重复
            // GDT 动态 framework 的嵌入由 PostProcessor 处理
            podfileContent.AppendLine("target 'UnityFramework' do");
            podfileContent.AppendLine($"  pod 'DirichletMediationSDK', '{SDKVersion}'");
            
            if (enableCsj)
            {
                podfileContent.AppendLine($"  pod 'DirichletMediationAdapterCSJ', '{SDKVersion}'");
            }

            if (enableGdt)
            {
                podfileContent.AppendLine($"  pod 'DirichletMediationAdapterGDT', '{SDKVersion}'");
            }

            // DirichletAdSDK (DRA adapter) is always included as core SDK
            podfileContent.AppendLine($"  pod 'DirichletMediationAdapterDRA', '{SDKVersion}'");

            podfileContent.AppendLine("end");
            podfileContent.AppendLine();
            
            // Post-install: 基础构建设置
            podfileContent.AppendLine("post_install do |installer|");
            podfileContent.AppendLine("  installer.pods_project.targets.each do |target|");
            podfileContent.AppendLine("    target.build_configurations.each do |config|");
            podfileContent.AppendLine("      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'");
            podfileContent.AppendLine("      config.build_settings['ENABLE_BITCODE'] = 'NO'");
            podfileContent.AppendLine("    end");
            podfileContent.AppendLine("  end");
            podfileContent.AppendLine("end");

            var podfilePath = Path.Combine(projectPath, "Podfile");
            File.WriteAllText(podfilePath, podfileContent.ToString());

            Debug.Log($"[DirichletMediation] Generated Podfile at {podfilePath}");
            Debug.Log($"[DirichletMediation] Adapters: CSJ={enableCsj}, GDT={enableGdt}, DirichletAdSDK=always");
        }

        private static void ModifyXcodeProject(string projectPath)
        {
            var projectFilePath = Path.Combine(projectPath, "Unity-iPhone.xcodeproj/project.pbxproj");
            var pbxProject = new PBXProject();
            pbxProject.ReadFromFile(projectFilePath);

#if UNITY_2019_3_OR_NEWER
            var targetGuid = pbxProject.GetUnityFrameworkTargetGuid();
            var mainTargetGuid = pbxProject.GetUnityMainTargetGuid();
#else
            var targetGuid = pbxProject.TargetGuidByName("Unity-iPhone");
            var mainTargetGuid = targetGuid;
#endif

            // Add required frameworks
            pbxProject.AddFrameworkToProject(targetGuid, "AdSupport.framework", true);
            pbxProject.AddFrameworkToProject(targetGuid, "AppTrackingTransparency.framework", true);
            pbxProject.AddFrameworkToProject(targetGuid, "SystemConfiguration.framework", false);
            pbxProject.AddFrameworkToProject(targetGuid, "Security.framework", false);
            pbxProject.AddFrameworkToProject(targetGuid, "CoreTelephony.framework", true);
            pbxProject.AddFrameworkToProject(targetGuid, "AVFoundation.framework", false);
            pbxProject.AddFrameworkToProject(targetGuid, "WebKit.framework", false);
            pbxProject.AddFrameworkToProject(targetGuid, "CoreLocation.framework", false);
            pbxProject.AddFrameworkToProject(targetGuid, "CoreMotion.framework", false);
            // TODO: 当 DirichletMediationAdapterCSJ 新版发布（podspec 中已包含 CoreVideo 依赖）后，
            //       可移除以下两行 CoreVideo 的手动添加。
            //       相关问题详见：dirichlet-mediation-ios-adapter-csj/Docs/ADS_CN_COREVIDEO_ISSUE.md
            //       此问题源于 Ads-CN (穿山甲) podspec 遗漏了 CoreVideo 依赖声明。
            pbxProject.AddFrameworkToProject(targetGuid, "CoreVideo.framework", false);  // Required by BUAdSDK (CSJ)
            pbxProject.AddFrameworkToProject(mainTargetGuid, "CoreVideo.framework", false);

            // Set build settings for framework target
            pbxProject.SetBuildProperty(targetGuid, "ENABLE_BITCODE", "NO");
            pbxProject.SetBuildProperty(targetGuid, "CLANG_ENABLE_MODULES", "YES");
            
            // Set build settings for main target
            pbxProject.SetBuildProperty(mainTargetGuid, "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES", "YES");
            
            // Set LD_RUNPATH_SEARCH_PATHS to allow dynamic frameworks to be found at runtime
            pbxProject.SetBuildProperty(mainTargetGuid, "LD_RUNPATH_SEARCH_PATHS", "$(inherited) @executable_path/Frameworks");
            pbxProject.SetBuildProperty(targetGuid, "LD_RUNPATH_SEARCH_PATHS", "$(inherited) @executable_path/Frameworks @loader_path/Frameworks");

            pbxProject.WriteToFile(projectFilePath);
            Debug.Log("[DirichletMediation] Modified Xcode project settings");
        }

        private static void ModifyInfoPlist(string projectPath)
        {
            var plistPath = Path.Combine(projectPath, "Info.plist");
            var plist = new PlistDocument();
            plist.ReadFromFile(plistPath);

            var rootDict = plist.root;

            // Add App Transport Security settings (allow HTTP for ad content)
            if (!rootDict.values.ContainsKey("NSAppTransportSecurity"))
            {
                var atsDict = rootDict.CreateDict("NSAppTransportSecurity");
                atsDict.SetBoolean("NSAllowsArbitraryLoads", true);
                Debug.Log("[DirichletMediation] Added NSAppTransportSecurity to Info.plist");
            }

            // Add User Tracking Usage Description (required for iOS 14+ IDFA access)
            if (!rootDict.values.ContainsKey("NSUserTrackingUsageDescription"))
            {
                rootDict.SetString(
                    "NSUserTrackingUsageDescription",
                    "This app uses advertising identifier to provide personalized ads and improve user experience."
                );
                Debug.Log("[DirichletMediation] Added NSUserTrackingUsageDescription to Info.plist");
            }

            // Add Location Usage Description (required by some ad networks)
            if (!rootDict.values.ContainsKey("NSLocationWhenInUseUsageDescription"))
            {
                rootDict.SetString(
                    "NSLocationWhenInUseUsageDescription",
                    "This app uses your location to provide location-based advertisements."
                );
                Debug.Log("[DirichletMediation] Added NSLocationWhenInUseUsageDescription to Info.plist");
            }

            // Add SKAdNetwork identifiers for attribution tracking
            AddSKAdNetworkIds(rootDict);

            plist.WriteToFile(plistPath);
            Debug.Log("[DirichletMediation] Modified Info.plist");
        }

        private static void AddSKAdNetworkIds(PlistElementDict rootDict)
        {
            if (rootDict.values.ContainsKey("SKAdNetworkItems"))
            {
                Debug.Log("[DirichletMediation] SKAdNetworkItems already exists, skipping");
                return;
            }

            // Add common SKAdNetwork IDs used by ad networks
            var skAdNetworkArray = rootDict.CreateArray("SKAdNetworkItems");
            
            var commonSkAdNetworkIds = new[]
            {
                "cstr6suwn9.skadnetwork",  // ByteDance/Pangle
                "4fzdc2evr5.skadnetwork",  // GDT/Tencent
                "t38b2kh725.skadnetwork",  // TapADN/Dirichlet
                "hs6bdukanm.skadnetwork",  // Common networks
                "v72qych5uu.skadnetwork",
                "ludvb6z3bs.skadnetwork",
                "cp8zw746q7.skadnetwork",
                "3sh42y64q3.skadnetwork",
                "c6k4g5qg8m.skadnetwork"
            };

            foreach (var skAdNetworkId in commonSkAdNetworkIds)
            {
                var dict = skAdNetworkArray.AddDict();
                dict.SetString("SKAdNetworkIdentifier", skAdNetworkId);
            }

            Debug.Log($"[DirichletMediation] Added {commonSkAdNetworkIds.Length} SKAdNetwork IDs to Info.plist");
        }

        /// <summary>
        /// 嵌入动态 frameworks 到主 App (Unity-iPhone)
        /// GDT SDK 使用动态 framework，必须嵌入到主 App 才能在运行时加载
        /// </summary>
        private static void EmbedDynamicFrameworks(string projectPath)
        {
            var enableGdt = EditorPrefs.GetBool("Dirichlet.iOS.EnableGDT", true);
            if (!enableGdt)
            {
                Debug.Log("[DirichletMediation] GDT adapter disabled, skipping dynamic framework embedding");
                return;
            }

            var projectFilePath = Path.Combine(projectPath, "Unity-iPhone.xcodeproj/project.pbxproj");
            var pbxProject = new PBXProject();
            pbxProject.ReadFromFile(projectFilePath);

            var mainTargetGuid = pbxProject.GetUnityMainTargetGuid();
            var gdtFrameworksPath = Path.Combine(projectPath, "Pods/GDTMobSDK/GDTFramework");

            var dynamicFrameworks = new[] { "GDTMobSDK.xcframework", "Tquic.xcframework" };

            foreach (var fw in dynamicFrameworks)
            {
                var fwPath = Path.Combine(gdtFrameworksPath, fw);
                if (!Directory.Exists(fwPath))
                {
                    Debug.LogWarning($"[DirichletMediation] Framework not found: {fwPath}");
                    continue;
                }

                var relativePath = $"Pods/GDTMobSDK/GDTFramework/{fw}";
                var fileGuid = pbxProject.AddFile(relativePath, relativePath, PBXSourceTree.Source);
                
                // Unity 2019.3+ Extensions API - 一行搞定嵌入！
                pbxProject.AddFileToEmbedFrameworks(mainTargetGuid, fileGuid);
                Debug.Log($"[DirichletMediation] Embedded dynamic framework: {fw}");
            }

            pbxProject.WriteToFile(projectFilePath);
            Debug.Log("[DirichletMediation] Dynamic frameworks embedding completed");
        }

        private static void RunPodInstall(string projectPath)
        {
            var podfilePath = Path.Combine(projectPath, "Podfile");
            if (!File.Exists(podfilePath))
            {
                Debug.LogWarning("[DirichletMediation] Podfile not found, skipping pod install");
                return;
            }

            Debug.Log("[DirichletMediation] Running 'pod install'...");
            Debug.Log("[DirichletMediation] Note: This may take a few minutes on first build or when adapters change.");

            try
            {
                // Try to find pod executable
                var podPath = FindPodExecutable();
                if (string.IsNullOrEmpty(podPath))
                {
                    Debug.LogWarning("[DirichletMediation] CocoaPods not found. Please install CocoaPods:");
                    Debug.LogWarning("  sudo gem install cocoapods");
                    Debug.LogWarning("Then run 'pod install' manually in:");
                    Debug.LogWarning($"  {projectPath}");
                    return;
                }

                var processInfo = new System.Diagnostics.ProcessStartInfo
                {
                    FileName = podPath,
                    Arguments = "install --repo-update",
                    WorkingDirectory = projectPath,
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    CreateNoWindow = true
                };
                
                // Set UTF-8 encoding to avoid CocoaPods encoding issues
                processInfo.EnvironmentVariables["LANG"] = "en_US.UTF-8";
                processInfo.EnvironmentVariables["LC_ALL"] = "en_US.UTF-8";

                using (var process = System.Diagnostics.Process.Start(processInfo))
                {
                    var output = process.StandardOutput.ReadToEnd();
                    var error = process.StandardError.ReadToEnd();
                    process.WaitForExit();

                    if (process.ExitCode == 0)
                    {
                        Debug.Log($"[DirichletMediation] pod install completed successfully");
                        if (!string.IsNullOrEmpty(output) && output.Length < 2000)
                        {
                            Debug.Log($"Output:\n{output}");
                        }
                    }
                    else
                    {
                        Debug.LogError($"[DirichletMediation] pod install failed with exit code {process.ExitCode}");
                        Debug.LogError($"Error:\n{error}");
                        if (!string.IsNullOrEmpty(output))
                        {
                            Debug.LogError($"Output:\n{output}");
                        }
                    }
                }
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"[DirichletMediation] Failed to run pod install: {ex.Message}");
                Debug.LogWarning("[DirichletMediation] Please run 'pod install' manually in the Xcode project directory:");
                Debug.LogWarning($"  cd {projectPath}");
                Debug.LogWarning("  pod install");
            }
        }

        private static string FindPodExecutable()
        {
            var possiblePaths = new[]
            {
                "/usr/local/bin/pod",
                "/opt/homebrew/bin/pod",
                "/usr/bin/pod",
                Path.Combine(System.Environment.GetEnvironmentVariable("HOME") ?? "", ".rbenv/shims/pod"),
                Path.Combine(System.Environment.GetEnvironmentVariable("HOME") ?? "", ".rvm/wrappers/default/pod")
            };

            foreach (var path in possiblePaths)
            {
                if (File.Exists(path))
                {
                    Debug.Log($"[DirichletMediation] Found pod at: {path}");
                    return path;
                }
            }

            // Try using 'which pod'
            try
            {
                var processInfo = new System.Diagnostics.ProcessStartInfo
                {
                    FileName = "which",
                    Arguments = "pod",
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    CreateNoWindow = true
                };

                using (var process = System.Diagnostics.Process.Start(processInfo))
                {
                    var output = process.StandardOutput.ReadToEnd().Trim();
                    process.WaitForExit();

                    if (process.ExitCode == 0 && !string.IsNullOrEmpty(output) && File.Exists(output))
                    {
                        Debug.Log($"[DirichletMediation] Found pod via 'which': {output}");
                        return output;
                    }
                }
            }
            catch
            {
                // Ignore
            }

            return null;
        }
    }
}

