// Code generated by Kitex v0.11.3. DO NOT EDIT.

package gatewayservice

import (
	"context"
	"errors"
	gate_way "gate_way_module/kitex_gen/gate_way"
	gateway_service "gate_way_module/kitex_gen/gateway_service"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UserMsg": kitex.NewMethodInfo(
		userMsgHandler,
		newUserMsgArgs,
		newUserMsgResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	gatewayServiceServiceInfo                = NewServiceInfo()
	gatewayServiceServiceInfoForClient       = NewServiceInfoForClient()
	gatewayServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return gatewayServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return gatewayServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return gatewayServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GatewayService"
	handlerType := (*gateway_service.GatewayService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "gateway_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func userMsgHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(gate_way.UserMsgReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(gateway_service.GatewayService).UserMsg(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserMsgArgs:
		success, err := handler.(gateway_service.GatewayService).UserMsg(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserMsgResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserMsgArgs() interface{} {
	return &UserMsgArgs{}
}

func newUserMsgResult() interface{} {
	return &UserMsgResult{}
}

type UserMsgArgs struct {
	Req *gate_way.UserMsgReq
}

func (p *UserMsgArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserMsgArgs) Unmarshal(in []byte) error {
	msg := new(gate_way.UserMsgReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserMsgArgs_Req_DEFAULT *gate_way.UserMsgReq

func (p *UserMsgArgs) GetReq() *gate_way.UserMsgReq {
	if !p.IsSetReq() {
		return UserMsgArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserMsgArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserMsgResult struct {
	Success *gate_way.UserMsgResp
}

var UserMsgResult_Success_DEFAULT *gate_way.UserMsgResp

func (p *UserMsgResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserMsgResult) Unmarshal(in []byte) error {
	msg := new(gate_way.UserMsgResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserMsgResult) GetSuccess() *gate_way.UserMsgResp {
	if !p.IsSetSuccess() {
		return UserMsgResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*gate_way.UserMsgResp)
}

func (p *UserMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserMsgResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserMsg(ctx context.Context, Req *gate_way.UserMsgReq) (r *gate_way.UserMsgResp, err error) {
	var _args UserMsgArgs
	_args.Req = Req
	var _result UserMsgResult
	if err = p.c.Call(ctx, "UserMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
