apiVersion: v1
kind: Service
metadata:
  labels:
    app: gate-server
  name: gate-server-in
  namespace: tank
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 11001
      targetPort: 11001
      protocol: TCP
      name: rpc
  selector:
    app: gate-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gate-server
  name: gate-server-out
  namespace: tank
spec:
  type: NodePort
  ports:
    - port: 32001
      nodePort: 32001
      targetPort: 12001
      protocol: TCP
      name: ws
  selector:
    app: gate-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-server
  namespace: tank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate-server
  template:
    metadata:
      labels:
        app: gate-server
    spec:
      containers:
        - name: gate-server
          image: docker.io/library/gate-server:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 11001
              name: rpc
              protocol: TCP
            - containerPort: 12001
              name: ws
              protocol: TCP
          env:
            - name: DEPLOYENV
              value: test
            - name: CONF_PATH
              value: /app/etc
            - name: CONF_FILE
              value: server-test.yaml
            - name: TZ
              value: Asia/Shanghai


