// Code generated by Kitex v0.11.3. DO NOT EDIT.
package servermgrservice

import (
	server "github.com/cloudwego/kitex/server"
	server_mgr_service "match_server/kitex_gen/server_mgr_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler server_mgr_service.ServerMgrService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler server_mgr_service.ServerMgrService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
