apiVersion: v1
kind: Service
metadata:
  labels:
    app: route-server
  name: route-server
  namespace: tank
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 11001
      targetPort: 11001
      protocol: TCP
      name: rpc
  selector:
    app: route-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-server
  namespace: tank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-server
  template:
    metadata:
      labels:
        app: route-server
    spec:
      containers:
        - name: route-server
          image: docker.io/library/route-server:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 11001
              name: rpc
              protocol: TCP
          env:
            - name: DEPLOYENV
              value: test
            - name: CONF_ENV_PATH
              value: /app/etc
            - name: CONF_ENV_FILE
              value: server-test.yaml
