// Code generated by Kitex v0.11.3. DO NOT EDIT.
package matchservice

import (
	server "github.com/cloudwego/kitex/server"
	match_service "match_server/kitex_gen/match_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler match_service.MatchService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler match_service.MatchService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
