// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0--rc2
// source: proto/user_center.proto

package user_center

import (
	context "context"
	common "gate_way_module/kitex_gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kid    string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	MacKey string `protobuf:"bytes,2,opt,name=macKey,proto3" json:"macKey,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_center_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_center_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_user_center_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *LoginReq) GetMacKey() string {
	if x != nil {
		return x.MacKey
	}
	return ""
}

type TapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar  string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender  string `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Openid  string `protobuf:"bytes,4,opt,name=openid,proto3" json:"openid,omitempty"`
	Unionid string `protobuf:"bytes,5,opt,name=unionid,proto3" json:"unionid,omitempty"`
}

func (x *TapInfo) Reset() {
	*x = TapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_center_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapInfo) ProtoMessage() {}

func (x *TapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_center_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapInfo.ProtoReflect.Descriptor instead.
func (*TapInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_center_proto_rawDescGZIP(), []int{1}
}

func (x *TapInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *TapInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *TapInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TapInfo) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *TapInfo) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

type TapBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *TapInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Now     int64    `protobuf:"varint,2,opt,name=now,proto3" json:"now,omitempty"`
	Success bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *TapBaseInfo) Reset() {
	*x = TapBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_center_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TapBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapBaseInfo) ProtoMessage() {}

func (x *TapBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_center_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapBaseInfo.ProtoReflect.Descriptor instead.
func (*TapBaseInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_center_proto_rawDescGZIP(), []int{2}
}

func (x *TapBaseInfo) GetData() *TapInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TapBaseInfo) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *TapBaseInfo) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       common.ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	Msg        string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ServerAddr string           `protobuf:"bytes,3,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"`
	ServerPort int32            `protobuf:"varint,4,opt,name=serverPort,proto3" json:"serverPort,omitempty"`
	TapInfo    *TapInfo         `protobuf:"bytes,5,opt,name=tapInfo,proto3" json:"tapInfo,omitempty"`
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_center_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_center_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_proto_user_center_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRsp) GetCode() common.ErrorCode {
	if x != nil {
		return x.Code
	}
	return common.ErrorCode(0)
}

func (x *LoginRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginRsp) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *LoginRsp) GetServerPort() int32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *LoginRsp) GetTapInfo() *TapInfo {
	if x != nil {
		return x.TapInfo
	}
	return nil
}

var File_proto_user_center_proto protoreflect.FileDescriptor

var file_proto_user_center_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x08, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x63, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x63, 0x4b, 0x65, 0x79,
	0x22, 0x7f, 0x0a, 0x07, 0x54, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x69,
	0x64, 0x22, 0x63, 0x0a, 0x0b, 0x54, 0x61, 0x70, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f,
	0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x07,
	0x74, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x74, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x27, 0x5a, 0x25,
	0x67, 0x61, 0x74, 0x65, 0x5f, 0x77, 0x61, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f,
	0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_center_proto_rawDescOnce sync.Once
	file_proto_user_center_proto_rawDescData = file_proto_user_center_proto_rawDesc
)

func file_proto_user_center_proto_rawDescGZIP() []byte {
	file_proto_user_center_proto_rawDescOnce.Do(func() {
		file_proto_user_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_center_proto_rawDescData)
	})
	return file_proto_user_center_proto_rawDescData
}

var file_proto_user_center_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_user_center_proto_goTypes = []interface{}{
	(*LoginReq)(nil),      // 0: user_center.LoginReq
	(*TapInfo)(nil),       // 1: user_center.TapInfo
	(*TapBaseInfo)(nil),   // 2: user_center.TapBaseInfo
	(*LoginRsp)(nil),      // 3: user_center.LoginRsp
	(common.ErrorCode)(0), // 4: common.ErrorCode
}
var file_proto_user_center_proto_depIdxs = []int32{
	1, // 0: user_center.TapBaseInfo.data:type_name -> user_center.TapInfo
	4, // 1: user_center.LoginRsp.code:type_name -> common.ErrorCode
	1, // 2: user_center.LoginRsp.tapInfo:type_name -> user_center.TapInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_center_proto_init() }
func file_proto_user_center_proto_init() {
	if File_proto_user_center_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_center_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_center_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_center_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TapBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_center_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_center_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_center_proto_goTypes,
		DependencyIndexes: file_proto_user_center_proto_depIdxs,
		MessageInfos:      file_proto_user_center_proto_msgTypes,
	}.Build()
	File_proto_user_center_proto = out.File
	file_proto_user_center_proto_rawDesc = nil
	file_proto_user_center_proto_goTypes = nil
	file_proto_user_center_proto_depIdxs = nil
}

var _ context.Context
