// Code generated by Kitex v0.15.1. DO NOT EDIT.

package user_center_service

import (
	"context"
	"user_server/kitex_gen/user_center"
)

type UserCenterService interface {
	Login(ctx context.Context, req *user_center.LoginReq) (res *user_center.LoginRsp, err error)
}
