// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package user_center_service

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	user_center "user_server/kitex_gen/user_center"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)
var _ = user_center.File_proto_user_center_proto
